# Generated by Django 4.0.3 on 2022-06-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта')),
                ('year', models.CharField(blank=True, max_length=200, null=True, verbose_name='Год выпуска')),
                ('vin', models.CharField(blank=True, max_length=200, null=True, verbose_name='ВИН')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Модель и марка')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('data', models.CharField(blank=True, max_length=200, verbose_name='Дата')),
                ('timedate', models.CharField(blank=True, max_length=200, null=True, verbose_name='Время')),
                ('problem', models.CharField(blank=True, max_length=200, null=True, verbose_name='Проблема')),
                ('adminComm', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий админа')),
                ('status', models.CharField(blank=True, choices=[('Принято в ремонт', 'Принято в ремонт'), ('Выполняется ремонт', 'Выполняется ремонт'), ('Ремонт выполнен', 'Ремонт выполнен'), ('Заявка закрыта', 'Заявка закрыта')], max_length=200, null=True, verbose_name='Статус')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
